import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Nav from '../componets/helper/Nav';
import { LSPFactory } from '@lukso/lsp-factory.js';

export default function Connect() {
      const connect=async()=>{
      const account=  await ethereum.request({ method: 'eth_requestAccounts', params: [] });
      console.log(account)
      const lspFactory = new LSPFactory(ethereum, {
      chainId: 2828,
      });
}
  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptolly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <div className={styles.main}>
        <div className={styles.content}>
          <h1>Connect to your <span>wallet</span></h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Odio urna in et enim facilisi vitae lorem suspendisse. Congue in.</p>
          <button onClick={connect}>Connect Now</button>
        </div>
        <div className={styles.image}>
          <img src="/image/connect.png"  />
        </div>
      </div>
    </div>
  )
}
