import styles from "../styles/Home.module.css"
import Communities from '../componets/helper/Communities'
import Connect from '../componets/helper/connect'
import Footer from '../componets/helper/Footer'
import Hero from '../componets/helper/Hero'
import Top from '../componets/helper/Top'
import Head from 'next/head'

export default function Home() {
  return (
    <div className={styles.container}>
       <Head>
        <title>Sagu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <Communities/>
      <Top/>
      <Connect/>
      <Footer/>
    </div>
  )
}
