import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cryptolly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <div className={styles.content}>
          <h1>Connect to your <span>wallet</span></h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Odio urna in et enim facilisi vitae lorem suspendisse. Congue in.</p>
          <button>Connect Now</button>
        </div>
        <div className={styles.image}>
          <img src="/image/connect.png"  />
        </div>
      </div>
    </div>
  )
}
