import Head from 'next/head';
import styles from '../../styles/auth/Connect.module.css'
import Nav from "../helper/Nav"
import { AuthContext } from '../../context/authContext';
import { useContext, useState } from 'react';
import { useRouter } from 'next/router';
import signinHandshake from '../../services/post/signinHandshake';
import signupHandshake from '../../services/post/signupHandshake';
import Web3 from "web3"
import axios from 'axios';
import Spinner from '../helper/spinner';


export default function SignIn() {
    const {address,setAddress,show,setShow}=useContext(AuthContext)
    const [isPending, setIsPending]=useState(false)
    const router=useRouter()
  
  const connect=async()=>{
    setIsPending(true)
    const web3 = new Web3(window.ethereum);
    
    
      const account=  await ethereum.request({ method: 'eth_requestAccounts', params: [] });
      console.log(account.toString())
      console.log("should connect");
      const signupShake = await signupHandshake({ walletAddress:account.toString() });
      console.log({signupShake})
      await setAddress(account.toString())
      if (signupShake.status== "error"){
        // signin user
    const signinShake = await signinHandshake({
      walletAddress: account.toString(),
    });
    const signature = await web3.eth.personal.sign(signinShake.signMessage, account.toString());
    const loginResponse = await axios.post("/api/apiSigninUser", {
      signature,
      walletAddress: account.toString(),
    });
    if (loginResponse.data.status == "error") {
      setIsPending(false);
      // alert(loginResponse.data.msg || "Something went wrong");
      console.log("bad error");
      return;
    }

    console.log({ loginResponsedata:loginResponse.data });  
      // alert("user loggedin succesfully")
    // setIsPending(false)
    return router.push("/dashboard")

      }
      if (signupShake.status == "success") {
        console.log("there is a success");
        // setHasSubmit(false);
        // setIsPending(false);
        // alert("setwalletshow true")
        return setShow(true);
      }


      
}
  return (
    <>
    <Nav/>
    <div className={styles.container}>
      <Head>
        <title>Sagu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.main}>
        <div className={styles.content}>
          <h1>Connect to your <span>wallet</span></h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Odio urna in et enim facilisi vitae lorem suspendisse. Congue in.</p>
          <button onClick={connect}>Connect Now</button>
        </div>
        <div className={styles.image}>
          <img src="/image/connect.png"  />
        </div>
      </div>
      <footer className={styles.footer}>
        <div className={styles.left}>
          <p>Privacy Policy</p>
          <p>Terms of Service</p>
          <p>Connect wallet</p>
        </div>
        <div className={styles.right}>
          <p>@2022 sagu . All Right Reserved</p>
          <p>Need help?</p>
        </div>
      </footer>
      
      {isPending && <Spinner/>}
    </div>
    </>
  )
}
