import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../../styles/auth/Connect.module.css'
import Nav from "../helper/Nav"
import { LSPFactory } from '@lukso/lsp-factory.js';

export default function SignIn
() {
      const connect=async()=>{
      const account=  await ethereum.request({ method: 'eth_requestAccounts', params: [] });
      console.log(account)
      const lspFactory = new LSPFactory(ethereum, {
      chainId: 2828,
      });
}
  return (
    <>
    <Nav/>
    <div className={styles.container}>
      <Head>
        <title>Cryptolly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className={styles.main}>
        <div className={styles.content}>
          <h1>Connect to your <span>wallet</span></h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
          Odio urna in et enim facilisi vitae lorem suspendisse. Congue in.</p>
          <button onClick={connect}>Connect Now</button>
        </div>
        <div className={styles.image}>
          <img src="/image/connect.png"  />
        </div>
      </div>
      <footer className={styles.footer}>
        <div className={styles.left}>
          <p>Privacy Policy</p>
          <p>Terms of Service</p>
          <p>Connect wallet</p>
        </div>
        <div className={styles.right}>
          <p>@2022 sagu . All Right Reserved</p>
          <p>Need help?</p>
        </div>
      </footer>
    </div>
    </>
  )
}
